### ISSUE TITLE
Systemic Interaction Framework (SIF) Implementation in LP MVP

### ISSUE THREAD

**Issue by erematorg** [erematorg/LP#61]
### Problem Description

The current implementation of entity interactions in LP with classic solution would be highly scripted and lacks flexibility. This approach does not scale well with the addition of new species, subspecies, or unique behaviors. We need a modular, data-driven framework that allows dynamic interactions between entities like animals, plants, and terrain, minimizing hardcoding and improving maintainability and scalability.

### Proposed Solution

Implement a Systemic Interaction Framework (SIF) that leverages general classes and JSON-defined attributes for entity creation and interaction. 
Inspired by ECS & Rule Based mixed approaches.
This framework will include:

- EntityFactory: Dynamically creates entities based on JSON data.
- EntityLoader: Manages loading and saving of entity data.
- InteractionManager: Handles interactions between entities based on their attributes.

### Alternatives Considered

- Scripted Approach: Continue with the current method of hardcoding interactions. This is less flexible and harder to maintain.
- ECS (Entity-Component-System): While ECS is powerful, it might be overkill for our current needs and could introduce unnecessary complexity.
- Rule Based Systems: Cannot extend to much to get everything about IRL related, would be too much cumbersome

### Additional Context

We aim to ensure that each entity’s attributes are correctly loaded and applied, validating the SIF concept for the MVP. This will demonstrate a dynamic and modular approach, allowing for more natural and diverse interactions in LP.

**Comment by M1thieu** [comment]
Reference video to understand the usage of this system (ECS inspired)
https://github.com/erematorg/LP/assets/18742831/c3b337cf-9465-4b6e-a6a3-3197ebf20965

**Comment by erematorg** [comment]
Closed by #68
